FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

ENV DOTNET_EnableWriteXorExecute=0

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore ./Api.sln
# Build and publish a release
RUN dotnet publish -c Release -o out ./Api.sln

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "DotNet.Docker.dll"]